name: "Setup"
description: "Setup Hatch"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: |
          3.11
          3.12
          3.13
    
    - name: Install Hatch
      shell: bash
      run: pip install hatch

    - name: Display Python version
      shell: bash
      run: python -c "import sys; print(sys.version)"
