name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.11
            3.12
            3.13
          cache: 'pip' # caching pip dependencies
      - name: Install Hatch
        run: pipx install hatch
      - name: Run tests
        run: hatch -vvv run tests:all


  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11
            3.12
            3.13
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"